definitions:
  model.UserAuth:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      userName:
        type: string
    type: object
info:
  contact:
    email: paradoxfm@mail.ru
    name: API Support
  description: This is api for beacon services
  license: {}
  title: Swagger API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserAuth'
            type: array
      summary: List accounts
      tags:
      - Пользователи users
    post:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserAuth'
            type: array
      summary: List accounts
      tags:
      - Пользователи users
swagger: "2.0"
