### авторизация
POST http://localhost:8070/api/v1/users/login
Content-Type: application/json

{
	"email": "evs343@ya.ru",
	"password": "password"
}

### запрос профиля
GET http://localhost:8070/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYxODMwNzYsIm9yaWdfaWF0IjoxNTM3NzgzMDc2LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.b2GMV1o-WTl8kEdvlqug_UT5MOp5tyZW7iS3N_0FiHY

###

### запрос истории
GET http://localhost:8070/api/v1/trackers/geo/history/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYxODMwNzYsIm9yaWdfaWF0IjoxNTM3NzgzMDc2LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.b2GMV1o-WTl8kEdvlqug_UT5MOp5tyZW7iS3N_0FiHY
{
	"tracker_id": 9e95aa86-bb0e-11e8-8aec-5452007d877e,
	"date_start":"",
	"date_end":"2018-12-04T15:30:45Z"
}

###

### работа la: 56.813248 lo: 60.59087
### вне 56.814017, 60.592747
### проверка алертов
POST http://localhost:7777/api/v1/heartbeat
Content-Type: application/json
Authorization: Basic aGVhcnQzNDkwMjM6czE1NkV6STA3ODIwQ3RzZkpodQ==

{
  "is_gps_source": true,
  "latitude": 56.814017,
  "longitude": 60.592747,
  "power": 99,
  "datetime": "2018-10-10T15:53:24+05:00",
  "device_id": "c60050f8255acc10"
}

###

### обновление push id
PUT http://localhost:8070/api/v1/users/me/push
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYyNTY0MzYsIm9yaWdfaWF0IjoxNTM3ODU2NDM2LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.WTK3UWQaja_6nKcuDu5QpxsGaVeIddjRegKwGMqviZ0

{
	"push_id": "dx46qZ3i48w:APA91bHDBHtCjLV1t5rcAy1ddo16oH2ycUFlE0wvkejSdpVtseC8KrjgivyZKT17bO3xK3BEqbZbuoca70t2A34PrWgzOlmt41dgBFzLX6Ofovk10jmcp2fDHMSLZSABrU7c6_X0YZe6CaKp2Ylb5cuTOtY0z5Oq-A"
}

###

###
GET http://localhost:8070/api/v1/geozones
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYyOTkyOTgsIm9yaWdfaWF0IjoxNTM3ODk5Mjk4LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.uRD-rhqSWG1E7L8OR_VikToFRjKPR0zzy4UCMh4Da6w

###

### обновление настроек треков
GET http://localhost:8070/api/v1/test/updtrack
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYyNTY0MzYsIm9yaWdfaWF0IjoxNTM3ODU2NDM2LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.WTK3UWQaja_6nKcuDu5QpxsGaVeIddjRegKwGMqviZ0

###

### проверка отправки push
GET http://localhost:8070/api/v1/test/push
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjc3MjA2NjIsIm9yaWdfaWF0IjoxNTM5MzIwNjYyLCJwcml2YXRlX2NsYWltX2lkIjoiZjc2ZGRkYTctYzk2Ny0xMWU3LWE5MzAtNTQ1MjAwN2Q4NzdlIn0.fDbOKWNLAFsCZswXFFC411eAX1cS36MGuerhXtja1YY

###

### получение гео зон пользхователя
GET http://localhost:8070/api/v1/geozones
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYxODMwNzYsIm9yaWdfaWF0IjoxNTM3NzgzMDc2LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.b2GMV1o-WTl8kEdvlqug_UT5MOp5tyZW7iS3N_0FiHY

###

POST http://localhost:8070/api/v1/users/password/reset
Content-Type: application/json

{
	"email": "paradoxfm@mail.ru"
}

###

###
POST http://localhost:7777/api/v1/heartbeat
Content-Type: application/json
Authorization: Basic aGVhcnQzNDkwMjM6czE1NkV6STA3ODIwQ3RzZkpodQ==

{
	"is_gps_source": true
}

###

### получение всех трекеров пользователя
GET http://localhost:8070/api/v1/trackers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIzMjYxODMwNzYsIm9yaWdfaWF0IjoxNTM3NzgzMDc2LCJwcml2YXRlX2NsYWltX2lkIjoiNTRkOTYyM2MtMTFhZi0xMWU4LWEyN2QtNTQ1MjAwN2Q4NzdlIn0.b2GMV1o-WTl8kEdvlqug_UT5MOp5tyZW7iS3N_0FiHY

###