POST http://localhost:8070/api/v1/users/login
Content-Type: application/json

{
  "username": "paraddopxfm@mail.ru",
  "password": "content"
}

###

POST http://localhost:8070/api/v1/users/password/reset
Content-Type: application/json

{
  "email": "paradoxfm@mail.ru"
}

###

POST http://194.213.117.101/api/rpc.php
Content-Type: application/json

{
  "id": 4,
  "jsonrpc": 2.0,
  "method": "getTransTypeTree",
  "params": {
    "ok_id": "3",
    "sid": "E85F1C7C-EE0D-4992-923E-CF3A4C0062FB"
  }
}

###

