// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-10-25 15:56:49.276122 +0500 +05 m=+0.645631701

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is api for beacon services",
        "title": "Swagger API",
        "contact": {
            "name": "API Support",
            "email": "paradoxfm@mail.ru"
        },
        "license": {},
        "version": "1.0"
    },
    "paths": {
        "/avatar/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Система"
                ],
                "summary": "Загрузка аватарки по id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id аватарки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AvatarResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/heartbeat": {
            "post": {
                "description": "Принимает координаты от смартфона, происходит: сохранение и проверка на вхождение в неозоны, обновление последних данных трекера",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Мониторинг"
                ],
                "summary": "Прием координат от смартфона",
                "parameters": [
                    {
                        "description": "Запрос с координатами и флагами устройства",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Heartbeat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers": {
            "post": {
                "description": "Создание нового трекера для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Создание нового трекера",
                "parameters": [
                    {
                        "description": "Запрос на создание треккера",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.TrackCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.TrackCreateResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/all": {
            "get": {
                "description": "Лист трекеров для пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Загрузить трекеры",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tracker"
                            }
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/avatar/{id}": {
            "put": {
                "description": "Обновление аватара трекера для пользователя (jpeg 250x250)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Обновление аватара трекера",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id трекера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "avatar",
                        "name": "avatar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AvatarIdResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/custom": {
            "post": {
                "description": "Лист выбранных трекеров для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Загрузить трекеры по id",
                "parameters": [
                    {
                        "description": "Запрос на отдельные трекеры",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.TracksByIdsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Tracker"
                            }
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/delete/{id}": {
            "delete": {
                "description": "Удаление трекера для авторизованного пользователя, если трекер привязан к нескольким пользователям, то только отвязка",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Удаление трекера",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id трекера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/find/{id}": {
            "get": {
                "description": "Загрузка трекера по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Загрузить трекер",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id трекера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.Tracker"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/geo/history": {
            "post": {
                "description": "Получение истории для трекера за период",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "История трекера",
                "parameters": [
                    {
                        "description": "Запрос истории треккера",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.TracksHistRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TrackHistoryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/trackers/update/{id}": {
            "put": {
                "description": "Обновление свойств трекера для пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Трекеры"
                ],
                "summary": "Обновление трекера",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id трекера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Запрос на редактирование трекера",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.TrackPrefRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Получение профиля пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Запрос профиля",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users/avatar": {
            "put": {
                "description": "Обновление аватара пользователя (jpeg 250x250)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Обновление аватара пользователя",
                "parameters": [
                    {
                        "description": "avatar",
                        "name": "avatar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.AvatarIdResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Авторизация пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Логин пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users/password": {
            "put": {
                "description": "Изменение пароля пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Изменение пароля",
                "parameters": [
                    {
                        "description": "Запрос на изменение пароля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users/password/reset": {
            "post": {
                "description": "Сброс пароля пользователя по email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Сброс пароля",
                "parameters": [
                    {
                        "description": "Запрос на сброс пароля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users/push": {
            "put": {
                "description": "Обновление push id пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Обновление push id пользователя",
                "parameters": [
                    {
                        "description": "Запрос с push id",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.UpdatePushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/users/signUp": {
            "post": {
                "description": "Регистрация пользователя email + password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Запрос на регистрацию",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.RegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/zone/all": {
            "get": {
                "description": "Получение списка зон для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Зоны"
                ],
                "summary": "Список зон",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.GeoZoneResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/zone/delete/{id}": {
            "delete": {
                "description": "Удаление зоны для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Зоны"
                ],
                "summary": "Удаление зоны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id зоны",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/zone/find/{id}": {
            "get": {
                "description": "Загрузка зоны для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Зоны"
                ],
                "summary": "Загрузка зоны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id зоны",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.GeoZoneResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/zone/save": {
            "post": {
                "description": "Создание зоны для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Зоны"
                ],
                "summary": "Создание зоны",
                "parameters": [
                    {
                        "description": "Запрос настройками зоны",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ZoneCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.GeoZoneResponse"
                        }
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/zone/snap/{id}": {
            "put": {
                "description": "Привязка зоны к списку трекеров",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Зоны"
                ],
                "summary": "Привязка зоны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id зоны",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Запрос привязки трекеров к зоне",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ZoneSnapRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        },
        "/zone/update/{id}": {
            "put": {
                "description": "Обновление настроек зоны для авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Зоны"
                ],
                "summary": "Обновление зоны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id зоны",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Запрос настройками зоны",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ZoneCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok"
                    },
                    "400": {
                        "description": "err"
                    },
                    "500": {
                        "description": "err"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AvatarIdResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "model.AvatarResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "base64"
                }
            }
        },
        "model.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "model.GeoZoneResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ZonePoint"
                    }
                },
                "trackers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Heartbeat": {
            "type": "object",
            "properties": {
                "datetime": {
                    "type": "string",
                    "example": "RFC3339"
                },
                "device_id": {
                    "type": "string"
                },
                "is_gps_source": {
                    "type": "boolean"
                },
                "is_gsm_source": {
                    "type": "boolean"
                },
                "is_low_power_alarm": {
                    "type": "boolean"
                },
                "is_sos_alarm": {
                    "type": "boolean"
                },
                "is_wifi_source": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "power": {
                    "type": "integer"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "model.ProfileResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "trackers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserTracker"
                    }
                }
            }
        },
        "model.RegistrationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "сonfirm": {
                    "type": "string"
                }
            }
        },
        "model.ResetPasswordRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "model.TrackCreateRequest": {
            "type": "object",
            "properties": {
                "equipment_id": {
                    "type": "string",
                    "example": "device id"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.TrackCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "model.TrackHistoryResponse": {
            "type": "object",
            "properties": {
                "datetime": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "model.TrackPrefRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "model.Tracker": {
            "type": "object",
            "properties": {
                "battery_power_last": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "device_type": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "latitude_last": {
                    "type": "number"
                },
                "longitude_last": {
                    "type": "number"
                },
                "signal_source": {
                    "type": "integer"
                },
                "signal_timestamp_last": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.TracksByIdsRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.TracksHistRequest": {
            "type": "object",
            "properties": {
                "date_end": {
                    "type": "string",
                    "example": "RFC3339"
                },
                "date_start": {
                    "type": "string",
                    "example": "RFC3339"
                },
                "tracker_id": {
                    "type": "string"
                }
            }
        },
        "model.UpdatePushRequest": {
            "type": "object",
            "properties": {
                "push_id": {
                    "type": "string"
                }
            }
        },
        "model.UserTracker": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "model.ZoneCreateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ZonePoint"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "model.ZonePoint": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        },
        "model.ZoneSnapRequest": {
            "type": "object",
            "properties": {
                "trackers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
